### ISSUE TITLE
Request to update NLD source files

### ISSUE THREAD

**Issue by robeweber** [sgofferj/TAK-ADSB-ID#3]
Hi,
Great job with this addon.

I have just updated the CIV, LEO and MIL txt files for The Netherlands (NLD).

Would you mind uploading and updating?

Thanks a bunch.
Kind regards,
Robert
[CIV.txt](https://github.com/user-attachments/files/17001918/CIV.txt)
[LEO.txt](https://github.com/user-attachments/files/17001655/LEO.txt)
[MIL.txt](https://github.com/user-attachments/files/17001656/MIL.txt)

**Comment by sgofferj** [comment]
I'll check them asap, thanks a lot!

**Comment by sgofferj** [comment]
Done. Thanks again!

A few remarks:
EC-135 is a light utility helicopter, i.e. a-f-A-M-H-U-L, not a-f-A-M-H-U-M (medium util helo)
According to my research, "4807dd"/"G-LGNA" is a civilian aircraft, operated by Logan Air. Not NLD AF.
"480d75"/"SQBBIRDY" appears to be a ground vehicle, so I changed the CoT type to a-f-G-E-V-C-U-M.
All the NH-90s with registration N-... appear to be operated by NLD Navy, not Air Force.
"484122","P4-VIP" appears to be registered to a private operator
"480000","PH-KZH" appears to be operated by KLM
