### ISSUE TITLE
Q: correct config for PiAware plus ADSBCOT

### ISSUE THREAD

**Issue by robeweber** [sgofferj/TAK-ADSB-ID#4]
Hi,

I was wondering if my configuration on a piAware Raspi is correct.
I have a local TAK Server plus on a different machine piAware and ADSBCOT correctly running. The data is populating nicely on the TAK Server.

If I want to use your json output as known_craft, is my config as follows correct?:

```
[adsbcot]
COT_URL = tcp://[**localIP**]:[**port**]
FEED_URL = http://localhost:8080/data/aircraft.json
POLL_INTERVAL = 10
KNOWN_CRAFT = /home/pi/cotdb_indexed.json
```

Where cotdb_indexed.json is from your git repository.
I noticed that I get error messages from cotdb.json, so I switched over to cotdb_indexed.json instead and no longer have error messages.

A heads-up would be nice. Thank you.
Kind regards
Robert

**Comment by sgofferj** [comment]
No idea, actually.  I'm just doing the database. The right place for this question is https://github.com/snstac/adsbcot/issues

**Comment by robeweber** [comment]
If anyone needs help with this feature and setup. Look at the following issue in a different repo:
[known_craft config issue](https://github.com/snstac/adsbcot/issues/47)
